spring:
  application:
    name: pstReader

  datasource:
    url: jdbc:postgresql://localhost:5432/pstReader
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB

  elasticsearch:
    rest:
      uris: http://localhost:9200  # Default URI for Elasticsearch
    username: elastic  # Elasticsearch username if authentication is enabled
    password: elastic  # Elasticsearch password if authentication is enabled

  data:
    cluster-names: elasticsearch
    node: localhost:9200
    elasticsearch:
      repositories:
        enabled: true